### PR TITLE
Update hamcrest

### PR DESCRIPTION
**Pull request by gilles**
Also use the main module, -core, -xxx are deprecated

### CODE REVIEW

**Comment by gilles** [comment]
@mattnworb

**Review by mattnworb — APPROVED** [review]
wanna bump the `version` too? maybe `1.2.x`?

**Comment by gilles** [comment]
make sense. done.

**Review by mattnworb — APPROVED** [review]
thanks 👍

**Comment by gilles** [comment]
I don't have merge/release privileges. Would you mind either adding me or merging. I can take care of the jackson update (2 related open PR) before we release

**Comment by mattnworb** [comment]
@gilles sure just let me know when you want a release cut

**Pull request merged**
