### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@mattnworb Addresses some comments you had in an email.

**Comment by dflemstr** [comment]
@davidxia @mattnworb it's tricky to maintain specs for dependency management like this, especially since less and less people are using Maven and will have to mentally translate into gradle/SBT etc.

I would encourage making the link to maven.org more visible instead since that will always list the latest versions and have copypastas for all major dependency management systems.

**Comment by mattnworb** [comment]
I agree with @dflemstr - it seems superfluous to me to list the maven coordinates for each and every module. It would make sense to me to link to maven.org as suggested and mention the groupId once and perhaps list out the artifact names. I don't think we have to tell users what the XML should look like.

**Review by mattnworb — CHANGES_REQUESTED** [review]
My suggestion would be to just have a block at the top like

```
## How to use
Each of these modules is published to Maven Central (add link) with the groupId of `com.spotify`. The list of modules available is:

- hamcrest-pojo
- hamcrest-java8 
etc
```

**Comment by davidxia** [comment]
Thanks. Updated

**Review by mattnworb — APPROVED** [review]

**Pull request merged**
